version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: monthly
    timezone: America/New_York
  open-pull-requests-limit: 10
- package-ecosystem: cargo
  directory: "/"
  # Update only the lockfile. We shouldn't update Cargo.toml unless it's for
  # a security issue, or if we need a new feature of the dependency.
  versioning-strategy: lockfile-only
  schedule:
    interval: monthly
    timezone: America/New_York
  open-pull-requests-limit: 10
