name: Docs

# Ensures that only one workflow task will run at a time. Previous deployments, if
# already in process, won't get cancelled. Instead, we let the first to complete
# then queue the latest pending workflow, cancelling any workflows in between
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      # doc source files
      - 'book/**'
      # source files; some md files include code snippets that we want to keep up to date
      - 'frost-*/**'
      # workflow definitions
      - '.github/workflows/docs.yml'
  push:
    branches:
      - main

# Sets permissions for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

env:
  RUST_LOG: info
  RUST_BACKTRACE: full
  RUST_LIB_BACKTRACE: full
  COLORBT_SHOW_HIDDEN: '1'

jobs:
  build:
    name: Build Docs (+beta)
    timeout-minutes: 45
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false

      - name: Install latest beta
        uses: dtolnay/rust-toolchain@beta

      - uses: Swatinem/rust-cache@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2.0.0
        with:
          mdbook-version: '0.4.18'

      # TODO: actions-mdbook does not yet have an option to install mdbook-mermaid https://github.com/peaceiris/actions-mdbook/issues/426
      - name: Install plugins
        run: |
          cargo install mdbook-mermaid
          cargo install mdbook-admonish

      - name: Build FROST book
        run: |
          mdbook build book/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        with:
          path: 'book/book'

  deploy:
    name: Deploy to GitHub Pages
    if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
    needs: build
    timeout-minutes: 10
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

